#!/usr/bin/env bash
# Provision writer + n dedicated DW EC2s (ClickHouse or TensorBase).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT}/instances.env"

AWS_REGION="${AWS_REGION:-us-west-2}"
KEY_NAME="${AWS_KEY_NAME:?Set AWS_KEY_NAME to your EC2 key pair name}"
SSH_USER="${SSH_USER:-ubuntu}"
INSTANCE_TYPE="${SPECTRA_AWS_INSTANCE_TYPE:-t3.xlarge}"
DW_N="${SPECTRA_BENCH_DW_N:-1}"
DW_KIND="${SPECTRA_MULTIDW_DW_KIND:?Set SPECTRA_MULTIDW_DW_KIND=clickhouse|tensorbase}"

if [[ "$DW_N" != "1" && "$DW_N" != "2" ]]; then
  echo "SPECTRA_BENCH_DW_N must be 1 or 2 (got ${DW_N})" >&2
  exit 1
fi
if [[ "$DW_KIND" != "clickhouse" && "$DW_KIND" != "tensorbase" ]]; then
  echo "SPECTRA_MULTIDW_DW_KIND must be clickhouse or tensorbase" >&2
  exit 1
fi

# AMI owner 099720109477 = Canonical Ubuntu.
AMI_ID="${AWS_AMI_ID:-$(aws ec2 describe-images --region "$AWS_REGION" \
  --owners 099720109477 \
  --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" \
            "Name=state,Values=available" \
  --query 'sort_by(Images,&CreationDate)[-1].ImageId' --output text)}"

MY_IP="$(curl -sf https://checkip.amazonaws.com || echo "0.0.0.0")"

VPC_ID="$(aws ec2 describe-vpcs --region "$AWS_REGION" \
  --filters Name=isDefault,Values=true \
  --query 'Vpcs[0].VpcId' --output text)"

SG_NAME="spectra-multidw-$(date +%Y%m%d%H%M)"
SG_ID="$(aws ec2 create-security-group --region "$AWS_REGION" \
  --group-name "$SG_NAME" --description "Spectra multi-DW writer+DW (SSH operator; DW ports SG-internal)" \
  --vpc-id "$VPC_ID" --query GroupId --output text)"

# SSH from operator
aws ec2 authorize-security-group-ingress --region "$AWS_REGION" --group-id "$SG_ID" \
  --ip-permissions \
  "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${MY_IP}/32,Description=ssh}]" \
  >/dev/null

# DW ports only within the security group (writer → DW)
aws ec2 authorize-security-group-ingress --region "$AWS_REGION" --group-id "$SG_ID" \
  --ip-permissions \
  "IpProtocol=tcp,FromPort=8123,ToPort=8123,UserIdGroupPairs=[{GroupId=${SG_ID},Description=clickhouse}]" \
  "IpProtocol=tcp,FromPort=9528,ToPort=9528,UserIdGroupPairs=[{GroupId=${SG_ID},Description=tensorbase}]" \
  >/dev/null

launch_one() {
  local name="$1"
  aws ec2 run-instances --region "$AWS_REGION" \
    --image-id "$AMI_ID" \
    --instance-type "$INSTANCE_TYPE" \
    --key-name "$KEY_NAME" \
    --security-group-ids "$SG_ID" \
    --block-device-mappings '[{"DeviceName":"/dev/sda1","Ebs":{"VolumeSize":40,"VolumeType":"gp3","DeleteOnTermination":true}}]' \
    --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${name}},{Key=Project,Value=spectra-multidw}]" \
    --query 'Instances[0].InstanceId' --output text
}

echo "Launching writer..."
WRITER_ID="$(launch_one "spectra-multidw-writer")"
DW_IDS=()
for i in $(seq 0 $((DW_N - 1))); do
  echo "Launching DW ${i} (${DW_KIND})..."
  DW_IDS+=("$(launch_one "spectra-multidw-dw-${DW_KIND}-${i}")")
done

ALL_IDS=("$WRITER_ID" "${DW_IDS[@]}")
echo "Waiting for instances: ${ALL_IDS[*]}"
aws ec2 wait instance-running --region "$AWS_REGION" --instance-ids "${ALL_IDS[@]}"

describe_ip() {
  local iid="$1" field="$2"
  aws ec2 describe-instances --region "$AWS_REGION" --instance-ids "$iid" \
    --query "Reservations[0].Instances[0].${field}" --output text
}

WRITER_PRIV="$(describe_ip "$WRITER_ID" PrivateIpAddress)"
WRITER_PUB="$(describe_ip "$WRITER_ID" PublicIpAddress)"
HW_SLUG="aws-${INSTANCE_TYPE//./-}"

{
  cat <<EOF
# Generated by provision.sh
AWS_REGION=${AWS_REGION}
AWS_KEY_NAME=${KEY_NAME}
SSH_USER=${SSH_USER}
SSH_KEY_PATH=${SSH_KEY_PATH:-$HOME/.ssh/${KEY_NAME}.pem}
SECURITY_GROUP_ID=${SG_ID}
SPECTRA_AWS_INSTANCE_TYPE=${INSTANCE_TYPE}
SPECTRA_BENCH_HARDWARE=${HW_SLUG}
SPECTRA_BENCH_DW_N=${DW_N}
SPECTRA_MULTIDW_DW_KIND=${DW_KIND}
INSTANCE_WRITER=${WRITER_ID}
WRITER_PRIVATE_IP=${WRITER_PRIV}
WRITER_PUBLIC_IP=${WRITER_PUB}
SPECTRA_WRITER_HOST=${WRITER_PUB}
EOF
  for i in $(seq 0 $((DW_N - 1))); do
    iid="${DW_IDS[$i]}"
    priv="$(describe_ip "$iid" PrivateIpAddress)"
    pub="$(describe_ip "$iid" PublicIpAddress)"
    cat <<EOF
INSTANCE_DW_${i}=${iid}
DW_${i}_PRIVATE_IP=${priv}
DW_${i}_PUBLIC_IP=${pub}
EOF
  done
} >"$ENV_FILE"

echo "Wrote ${ENV_FILE}"
cat "$ENV_FILE"
