#!/usr/bin/env bash
# Launch a single EC2 for co-located ClickHouse + TensorBase (E2E + bench).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT}/instances.env"

AWS_REGION="${AWS_REGION:-us-west-2}"
KEY_NAME="${AWS_KEY_NAME:?Set AWS_KEY_NAME to your EC2 key pair name}"
SSH_USER="${SSH_USER:-ubuntu}"
# t3.large (~8GiB / burstable) OOMs or starves SSH under firehose; default to t3.xlarge.
INSTANCE_TYPE="${SPECTRA_AWS_INSTANCE_TYPE:-t3.xlarge}"

# AMI owner 099720109477 = Canonical Ubuntu.
AMI_ID="${AWS_AMI_ID:-$(aws ec2 describe-images --region "$AWS_REGION" \
  --owners 099720109477 \
  --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" \
            "Name=state,Values=available" \
  --query 'sort_by(Images,&CreationDate)[-1].ImageId' --output text)}"

MY_IP="$(curl -sf https://checkip.amazonaws.com || echo "0.0.0.0")"

SG_NAME="spectra-aws-$(date +%Y%m%d%H%M)"
VPC_ID="$(aws ec2 describe-vpcs --region "$AWS_REGION" \
  --filters Name=isDefault,Values=true \
  --query 'Vpcs[0].VpcId' --output text)"

SG_ID="$(aws ec2 create-security-group --region "$AWS_REGION" \
  --group-name "$SG_NAME" --description "Spectra AWS E2E/bench host (CH+TB co-located)" \
  --vpc-id "$VPC_ID" --query GroupId --output text)"

aws ec2 authorize-security-group-ingress --region "$AWS_REGION" --group-id "$SG_ID" \
  --ip-permissions \
  "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${MY_IP}/32,Description=ssh}]" \
  >/dev/null

IID="$(aws ec2 run-instances --region "$AWS_REGION" \
  --image-id "$AMI_ID" \
  --instance-type "$INSTANCE_TYPE" \
  --key-name "$KEY_NAME" \
  --security-group-ids "$SG_ID" \
  --block-device-mappings '[{"DeviceName":"/dev/sda1","Ebs":{"VolumeSize":40,"VolumeType":"gp3","DeleteOnTermination":true}}]' \
  --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=spectra-aws},{Key=Project,Value=spectra-aws}]" \
  --query 'Instances[0].InstanceId' --output text)"

echo "Waiting for ${IID}..."
aws ec2 wait instance-running --region "$AWS_REGION" --instance-ids "$IID"

PRIVATE_IP="$(aws ec2 describe-instances --region "$AWS_REGION" --instance-ids "$IID" \
  --query 'Reservations[0].Instances[0].PrivateIpAddress' --output text)"
PUBLIC_IP="$(aws ec2 describe-instances --region "$AWS_REGION" --instance-ids "$IID" \
  --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)"

HW_SLUG="aws-${INSTANCE_TYPE//./-}"
cat >"$ENV_FILE" <<EOF
# Generated by provision.sh
AWS_REGION=${AWS_REGION}
AWS_KEY_NAME=${KEY_NAME}
SSH_USER=${SSH_USER}
SSH_KEY_PATH=${SSH_KEY_PATH:-$HOME/.ssh/${KEY_NAME}.pem}
SECURITY_GROUP_ID=${SG_ID}
INSTANCE_SMOKE=${IID}
SMOKE_IP=${PRIVATE_IP}
SMOKE_PUBLIC_IP=${PUBLIC_IP}
SPECTRA_E2E_HOST=${PUBLIC_IP}
SPECTRA_BENCH_HARDWARE=${HW_SLUG}
SPECTRA_AWS_INSTANCE_TYPE=${INSTANCE_TYPE}
EOF

echo "Wrote ${ENV_FILE}"
cat "$ENV_FILE"
